# Generated by Django 6.0.5 on 2026-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='game_logos/'),
        ),
    ]
