# Generated by Django 6.0.5 on 2026-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secret_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
